version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      ./compose.env
    ports:
      - 5432
    volumes:
    - db_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.3-alpine
    hostname: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

  gql-server:
    env_file:
      ./compose.env
    depends_on:
      - postgres
      - redis
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
      - 9229:9229

volumes:
    db_data:

